[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "payment weird material bullet side brand enlist subject slice weekend venture replace winner coin exotic change uncle predict bring parrot physical climb source game"
